version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: runbooks-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: runbooks_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - runbooks-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: runbooks-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/runbooks_db?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      API_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    networks:
      - runbooks-network
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: runbooks-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - runbooks-network
    command: npm run dev -- --host

volumes:
  mongodb_data:

networks:
  runbooks-network:
    driver: bridge
